trigger:
  branches:
    include:
      - main 

pool:
  name: 'default'
  demands:
    - agent.name -equals agente-windows

variables:
  imageName: 'entregable5-app'
  imageTag: '$(Build.BuildId)'
  acrLoginServer: 'entregable5acr.azurecr.io'

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build and Push image
    steps:
      # Si tu agente no tiene Docker, descomenta esto:
      # - task: DockerInstaller@0
      #   inputs:
      #     dockerVersion: '17.09.0-ce'

      - task: Docker@2
        displayName: Build and Push image to ACR
        inputs:
          containerRegistry: 'entregable5acr-connection' # Service Connection a tu ACR
          repository: '$(imageName)'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            $(imageTag)

- stage: DeployToContainerApp
  displayName: Deploy to Azure Container App
  dependsOn: BuildAndPush
  jobs:
  - job: Deploy
    displayName: Deploy to Container App
    steps:
      - task: AzureCLI@2
        displayName: Deploy to Azure Container App
        inputs:
          azureSubscription: 'entregable5-azure-connection' # ARM connection
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az containerapp update \
              --name entregable5containerapp \
              --resource-group IAEntregable5group \
              --image $(acrLoginServer)/$(imageName):$(imageTag) \
              --set-env-vars \
                AZURE_OPENAI_API_KEY=$(AZURE_OPENAI_API_KEY) \
                OPENAI_API_VERSION=$(OPENAI_API_VERSION) \
                AZURE_OPENAI_ENDPOINT=$(AZURE_OPENAI_ENDPOINT) \
                AZURE_OPENAI_DEPLOYMENT=$(AZURE_OPENAI_DEPLOYMENT) \
                MYSQL_DATABASE=$(MYSQL_DATABASE) \
                MYSQL_USER=$(MYSQL_USER) \
                MYSQL_PASSWORD=$(MYSQL_PASSWORD) \
                MYSQL_ROOT_PASSWORD=$(MYSQL_ROOT_PASSWORD) \
                DATABASE_URL=$(DATABASE_URL) \
                APP_SECRET_KEY=$(APP_SECRET_KEY)
        env:
          AZURE_OPENAI_API_KEY: $(AZURE_OPENAI_API_KEY)
          OPENAI_API_VERSION: $(OPENAI_API_VERSION)
          AZURE_OPENAI_ENDPOINT: $(AZURE_OPENAI_ENDPOINT)
          AZURE_OPENAI_DEPLOYMENT: $(AZURE_OPENAI_DEPLOYMENT)
          MYSQL_DATABASE: $(MYSQL_DATABASE)
          MYSQL_USER: $(MYSQL_USER)
          MYSQL_PASSWORD: $(MYSQL_PASSWORD)
          MYSQL_ROOT_PASSWORD: $(MYSQL_ROOT_PASSWORD)
          DATABASE_URL: $(DATABASE_URL)
          APP_SECRET_KEY: $(APP_SECRET_KEY)