trigger:
  branches:
    include:
      - main 

pool:
  name: 'default'
  demands:
    - agent.name -equals agente-windows

variables:
  imageName: 'entregable5-app'
  imageTag: '$(Build.BuildId)'
  acrLoginServer: 'entregable5acr.azurecr.io'

stages:
- stage: Test
  displayName: Run Tests
  jobs:
    - job: UnitTests
      displayName: Run unit and integration tests
      steps:
        - checkout: self
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.11'
            addToPath: true
        - script: |
            pip install -r requirements.txt
            pip install pytest pytest-cov
            pytest test/ --maxfail=1 --disable-warnings --junitxml=test-results.xml
          displayName: 'Run pytest'
        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: 'test-results.xml'
            failTaskOnFailedTests: true
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build and Push image
    steps:
      - task: Docker@2
        displayName: Build and Push image to ACR
        inputs:
          containerRegistry: 'entregable5acr-connection' # Service Connection a tu ACR
          repository: '$(imageName)'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            $(imageTag)

- stage: DeployToContainerApp
  displayName: Deploy to Azure Container App
  dependsOn: BuildAndPush
  jobs:
  - job: Deploy
    displayName: Deploy to Container App
    steps:
      - task: AzureCLI@2
        displayName: Deploy to Azure Container App
        inputs:
          azureSubscription: 'entregable5-azure-connection' # ARM connection
          scriptType: 'ps'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az containerapp update --name entregable5containerapp --resource-group IAEntregable5group --image $(acrLoginServer)/$(imageName):$(imageTag) --set-env-vars AZURE_OPENAI_API_KEY=$(AZURE_OPENAI_API_KEY) OPENAI_API_VERSION=$(OPENAI_API_VERSION) AZURE_OPENAI_ENDPOINT=$(AZURE_OPENAI_ENDPOINT) AZURE_OPENAI_DEPLOYMENT=$(AZURE_OPENAI_DEPLOYMENT) MYSQL_DATABASE=$(MYSQL_DATABASE) MYSQL_USER=$(MYSQL_USER) MYSQL_PASSWORD=$(MYSQL_PASSWORD) MYSQL_ROOT_PASSWORD=$(MYSQL_ROOT_PASSWORD) DATABASE_URL=$(DATABASE_URL) APP_SECRET_KEY=$(APP_SECRET_KEY)
        env:
          AZURE_OPENAI_API_KEY: $(AZURE_OPENAI_API_KEY)
          OPENAI_API_VERSION: $(OPENAI_API_VERSION)
          AZURE_OPENAI_ENDPOINT: $(AZURE_OPENAI_ENDPOINT)
          AZURE_OPENAI_DEPLOYMENT: $(AZURE_OPENAI_DEPLOYMENT)
          MYSQL_DATABASE: $(MYSQL_DATABASE)
          MYSQL_USER: $(MYSQL_USER)
          MYSQL_PASSWORD: $(MYSQL_PASSWORD)
          MYSQL_ROOT_PASSWORD: $(MYSQL_ROOT_PASSWORD)
          DATABASE_URL: $(DATABASE_URL)
          APP_SECRET_KEY: $(APP_SECRET_KEY)
